using System.Reflection.Metadata;
using DeveloperSample.ClassRefactoring.Model.Enums;

namespace DeveloperSample.ClassRefactoring.Model;

// Make class static no need to instantiate a factory to get a swallow unless we are going to use the factory to keep track of other details related to the sparrow or sparrows generated by a specific factory.
public static class SwallowFactory
{
    public static Swallow GetSwallow(SwallowType swallowType) => new(swallowType);
}